/**
 * Scaffold command — produce a minimal project layout:
 *   <project>/
 *     content/content.json
 *     content/ink/example.ink
 *     package.json    (with workspace pnpm reference)
 *     vite.config.ts  (using vnPlugin)
 *     src/main.tsx    (imports VN runtime)
 *     index.html
 */
import type { BuildContentOptions } from "vn-asset-pipeline";

export interface ScaffoldOptions {
  outDir: string;
  gameName?: string;
  packageManager?: "pnpm" | "npm";
  /** If true, scaffold a single demo storyline "example-heshui". */
  demo?: boolean;
}

export interface ScaffoldOutput {
  files: Array<{ path: string; content: string }>;
}

export function scaffoldProject(opts: ScaffoldOptions): ScaffoldOutput {
  const name = opts.gameName ?? "my-historical-vn";
  const files: Array<{ path: string; content: string }> = [];

  files.push({
    path: `${opts.outDir}/content/content.json`,
    content: JSON.stringify(sampleContent(name), null, 2) + "\n",
  });
  files.push({
    path: `${opts.outDir}/content/ink/example-heshui.ink`,
    content: sampleInk(),
  });
  files.push({
    path: `${opts.outDir}/vite.config.ts`,
    content: `import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\nimport { vnPlugin } from "vn-build-tools";\n\nexport default defineConfig({\n  plugins: [react(), vnPlugin({ contentDir: "content" })],\n});\n`,
  });
  files.push({
    path: `${opts.outDir}/package.json`,
    content: JSON.stringify({
      name,
      private: true,
      version: "0.1.0",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        "vn-runtime-react": "workspace:*",
        "vn-game-systems": "workspace:*",
        "vn-content-schemas": "workspace:*",
        "ink-vn-core": "workspace:*",
      },
      devDependencies: {
        vite: "^6.0.0",
        "@vitejs/plugin-react": "^4.3.0",
        "vn-build-tools": "workspace:*",
        typescript: "^5.9.3",
      },
    }, null, 2) + "\n",
  });
  files.push({
    path: `${opts.outDir}/tsconfig.json`,
    content: JSON.stringify({
      compilerOptions: {
        target: "ES2022", module: "ESNext", moduleResolution: "bundler",
        jsx: "react-jsx", strict: true, esModuleInterop: true, skipLibCheck: true,
        lib: ["ES2022", "DOM", "DOM.Iterable"],
      },
      include: ["src/**/*", "vite.config.ts"],
    }, null, 2) + "\n",
  });
  files.push({
    path: `${opts.outDir}/index.html`,
    content: `<!doctype html>\n<html lang="zh-CN">\n<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${name}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n`,
  });
  files.push({
    path: `${opts.outDir}/src/main.tsx`,
    content: `import React from "react";\nimport { createRoot } from "react-dom/client";\nimport { VNApp } from "vn-runtime-react";\nimport content from "virtual:vn-content";\nimport "vn-ui-components/styles.css";\n\ncreateRoot(document.getElementById("root")!).render(\n  <React.StrictMode>\n    <VNApp content={content as any} />\n  </React.StrictMode>\n);\n`,
  });
  files.push({
    path: `${opts.outDir}/README.md`,
    content: `# ${name}\n\nGenerated by vn-build-tools scaffold.\n\n## Commands\n\n- pnpm dev  — launch browser\n- pnpm build — build static site\n- pnpm vn-build scaffold demo-ink  — add another storyline\n\n## Edit content\n\n- content/content.json — metadata, character, series, storylines\n- content/ink/*.ink — Ink story scripts (tag syntax from ink-vn-core)\n`,
  });

  void opts.packageManager;
  void opts.demo;
  void 0 as unknown as BuildContentOptions;
  return { files };
}

function sampleContent(gameName: string) {
  return {
    schema_version: "1.0.0",
    game_name: gameName,
    default_theme: "inkWash",
    default_language: "zh-CN",
    series: [{
      id: "example", name: "示例章节", tagline: "上古治水", era: "xia",
      order: 1, glyph: "禹", accent: "#3a8c6e",
      bg_from: "#1a1f1a", bg_to: "#0f1510", coming_soon: false,
    }],
    characters: [{
      id: "yu", name: "禹", era: "xia", order: 1, dynasty_order: 1,
      title: "大禹", glyph: "禹", accent: "#3a8c6e",
      classical_quote: "禹抑洪水，十三年过家不入门。",
      historical_source: "史记·夏本纪",
      description: "上古治水英雄，禹步传说的主角。",
    }],
    storylines: [{
      id: "example-heshui", series: "example",
      title: "治水问道", subtitle: "禹与洪水",
      protagonist: "yu", cast: [], mode: "official",
      ink_path: "example-heshui.ink", difficulty: 1,
      synopsis: "尧帝命禹治水，三过家门而不入。",
    }],
    backgrounds: [{ id: "riverbank", series: "example", path: "bgs/riverbank.jpg", tags: ["outdoor", "day"] }],
    classics: { name: "典籍", chapters: [] },
    achievements: [{
      id: "yu_cleared", name: "禹功已成", rarity: 2, group: "general",
      trigger: { kind: "storyline_clear", storyline_id: "example-heshui" },
    }],
    minigames: [],
    bgm: { tracks: [] },
  };
}

function sampleInk(): string {
  return `VAR __storyline_id = "example-heshui"\nVAR mg_result = 0\nVAR mg_score = 0\n\n=== example-heshui ===\n\n青月: 上古之时，洪水滔天。\n#bg:riverbank #show:yu:stern:center\n禹: 水之不息，何以绥之？\n\n* 鲧堵之\n  禹: 堵而愈溢，非长策。\n  -> decide\n* 疏导之\n  禹: 开九州，通九道——或可。\n  -> decide\n\n= decide =\n#tag:true_end #kind:storyline_end\n青月: 十三年过家门而不入，功成。\n-> DONE\n`;
}
